### ISSUE TITLE
Composer custom vendor dir

### ISSUE THREAD

**Issue by deankinns** [koala-framework/composer-extra-assets#16]
if i set config > vendor-dir in my composer.json to somewhere other than "vendor" then i get this error while running a composer update command:

[Composer\Downloader\TransportException]                                                                                                                                              
  The "https://nodejs.org/dist/v4.1.2/node-v4.1.2-linux-x64.tar.gz" file could not be written to vendor/node-v4.1.2-linux-x64.tar.gz: failed to open stream: No such file or directory  

I assume this is because that config is not being picked up.

**Comment by nsams** [comment]
Please report this bug to https://github.com/thecodingmachine/nodejs-installer

Possible workaround: install nodejs globally (thru your package manager) and nodejs-installer won't need to download it locally.
