### ISSUE TITLE
bower modules not installed under v2.0.2 and symfony3

### ISSUE THREAD

**Issue by robertfausk** [koala-framework/composer-extra-assets#22]
In the extra segment I have following like:
```JS
# composer.json
        "require-bower-dev": {
            "jquery": "^2.0"
        }
```

Sadly there are no bower modules installed.
If you need more information then please tell me.

**Comment by nsams** [comment]
is this in your root composer.json?

**Comment by robertfausk** [comment]
Yes, it is.

**Comment by nsams** [comment]
Replace `"require-bower-dev"` with `"require-dev-bower"` and it will work correctly.
