### ISSUE TITLE
Plugin was skipped in composer 1.2

### ISSUE THREAD

**Issue by Sogl** [koala-framework/composer-extra-assets#23]
Hello!

Just updated `composer` to 1.2-dev (on Linux Ubuntu 14.04) and tried to `composer update` in Koala Framework:
```
The "koala-framework/composer-extra-assets" plugin was skipped because it requires a Plugin API
version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run
composer update with the "--no-plugins" option.
```

This error means that new API isn't supported yet? Can I correctly update dependencies with 1.2 version?
I stopped updating process because it's on my production server.

p.s. On Windows with composer version 1.1.0 all works fine and file `composer-extra-assets.lock` was added to the root folder.

**Comment by nsams** [comment]
fixed with composer-extra-assets 1.1 and 1.2 which should be compatible with composer 1.1+

**Comment by Sogl** [comment]
Ok, but with KWF 3.8 branch this warning exists. How to fix?

**Comment by nsams** [comment]
Kwf requires composer-extra-assets 1.1.* , so a composer update should get the new release.

**Comment by mhabsaoui** [comment]
Hi,

Any idea on why release v2.0.8 still requires composer-plugin-api ^1.0 on Composer v2 ?

![image](https://github.com/koala-framework/composer-extra-assets/assets/18755135/1092771f-eb3d-4ac9-81dd-234b8e47d3c1)

Thanks
