### ISSUE TITLE
Existing bower.json

### ISSUE THREAD

**Issue by letstalk-nl** [koala-framework/composer-extra-assets#30]
I have a bower.json for my project in the root and a plugin of my own that has specific bower dependencies as well. As I do not wish to add the plugin bower dependencies to my project's bower.json I was hoping I could use this plugin. It however notifies me that it cannot install the plugin's bower dependencies since there already exists a bower.json in the root.

Would it be possible to merge those dependencies? I'm planning on making a fork and pull request but I'm wondering if it goes against your own idea of what your plugin should be doing.

**Comment by nsams** [comment]
The plugin is in it's own composer package I suppose.

Why can't you use composer.json for both? You need composer install/update anyway.

**Comment by letstalk-nl** [comment]
That's a good option.. Hadn't thought of that yet! Thanks for the suggestion :)
