### ISSUE TITLE
Install nodejs locally if not found

### ISSUE THREAD

**Issue by nsams** [koala-framework/composer-extra-assets#4]
Integrate this package once it's stable:

https://github.com/thecodingmachine/nodejs-installer

**Comment by moufmouf** [comment]
Hi @nsams ,

Just opened a pull request (#5) to improve compatibility between nodejs-installer and composer-extra-assets.
I was wondering: do you see anything that could be improved to "nodejs-installer" that could help?
I'm considering tagging the current release as 1.0.0, but I'd like some feedback first.
If you think there is any interesting missing feature, let me know! Otherwise, I'll tag the release.

**Comment by nsams** [comment]
Hm, interesting.

My thoughts:

Is modifying the $PATH a standard solution or more a hack? I don't have the best feeling with it.

What I had in mind: composer-extra-assets should require nodejs-installer and use the nodejs by using `vendor/bin/node` instead of `node`. That would not require modifying $PATH.

What is missing in nodejs-installer is that not only the root package minimumVersion etc. is fetched.

What do you think?

**Comment by moufmouf** [comment]
Hi @nsams ,

> Is modifying the $PATH a standard solution or more a hack? I don't have the best feeling with it.

I understand your reluctance, it is indeed a hack. I made it an option `includeBinInPath` that is disabled by default.

> What is missing in nodejs-installer is that not only the root package minimumVersion etc. is fetched.

Good news, I got rid of "minimumVersion". Now, there is only one option "version" that accepts constraints just like NodeJS (for instance: "~0.11"). Also, this option is fetched and merged from all packages, so any package can add a particular constraint on the NodeJS version and the plugin will try to find the best matching version from all the constraint of all the existing packages.

This time, I believe it's ready. Anything else I can improve? Shall I release 1.0?

**Comment by nsams** [comment]
> Good news, I got rid of "minimumVersion". Now, there is only one option "version" that > accepts constraints just like NodeJS (for instance: "~0.11"). Also, this option is fetched > and merged from all packages, so any package can add a particular constraint on the NodeJS version and the plugin will try to find the best matching version from all the constraint of all the existing packages.

Cool, thanks.

I have created a PR for that integrates nodejs-installer: #6
Do you think that's the way to go?

> This time, I believe it's ready. Anything else I can improve? Shall I release 1.0?

I didn't test on other platforms than linux yet, but other than that it's ready for release.

**Comment by nsams** [comment]
#6 is merged
