### ISSUE TITLE
Installation directory for Bower / NPM dependencies

### ISSUE THREAD

**Issue by moufmouf** [koala-framework/composer-extra-assets#7]
Hi @nsams ,

I'm trying to build a ["gulp-installer" package](https://github.com/thecodingmachine/gulp-installer), based on *composer-extra-assets* and I'm currently facing an issue.

My whole idea was to define a NPM dependency in ["gulp-installer" composer.json](https://github.com/thecodingmachine/gulp-installer/blob/1.0/composer.json), then, I would let the user define it's own set of NPM plugins in the main *composer.json* file (see last sample in the README [here](https://github.com/thecodingmachine/gulp-installer)).

My problem is that *composer-extra-assets* is not "merging" the NPM dependencies in the global package. Instead, it will install "node_modules" directories in each composer package directory.

So gulp is installed in *vendor/mouf/gulp-installer/node_modules*, while my gulp plugins are installed in *node_modules*. Is there a reason you decided to put individual *node_modules* directories into the composer package directory? Would you accept a pull-request that adds an option to change this behaviour and merge everything in the main directory?

**Comment by nsams** [comment]
Reason for that is that npm also works that way - for node packages it usually doesn't make sense to merge dependencies.

Idea: what if composer-extra-assets would create a vendor/bin/ script for every node_modules/.bin/ script (root packages only) - which would also include gulp If installed as root dependency.

That would not make gulp-installer necessary at all :)

What do you think?

**Comment by nsams** [comment]
now implemented
